### ISSUE TITLE
Parse errors

### ISSUE THREAD

**Issue by ipapusha** [u-t-autonomous/sydar#4]
The following files lead to parse errors:
`examples/pftm16_ex1.miu`
`examples/pftm16_ex2.miu`

**Comment by sahabi** [comment]
The parse error was due to A = [[2,-2],[1,0]; not having a closing bracket, therefore the bug is in the example file. It would be nice to check for such cases and alert the user. I'll keep this issue open until I add this feature.

**Comment by sahabi** [comment]
Will close and add it to this ticket: https://github.com/u-t-autonomous/sydar/issues/5
