### ISSUE TITLE
Testing pftm16_ex2 & pftm16_ex1

### ISSUE THREAD

**Issue by sahabi** [u-t-autonomous/sydar#9]
I made a few changes to make these two example files work. I don't have MATLAB right now to test the generated code.

**Comment by sahabi** [comment]
Both examples output a valid MATLAB code. Can you verify the correctness of the code @ipapusha?

**Comment by ipapusha** [comment]
My testing gave different results than `twodim_example.m` and `complex_example.m`, but that doesn't mean that sydar is wrong. We need to write up more meaningful simulations to know for sure. I'll add that as a separate issue.
